import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Providers from "./providers";
import { Toaster } from "@/components/ui/toaster";
import { SocketProvider } from "@/context/SocketContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "StuSp",
  description: "Generated by create next app",
  icons: "/StuSp.svg",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className)} suppressHydrationWarning={true}>
        <SocketProvider>
          <Providers>
            {children}

            <Toaster />
          </Providers>
        </SocketProvider>
      </body>
    </html>
  );
}
